export { Education } from './education/education.component'
export { ExpertiseContent } from './expertises/expertises.componet'
export { MainSkillsContent } from './main-skills/main-skills-content.component'
export { IntroductionContent } from './introduction/introduction-content.component'
export { Contact } from './contact/contact.component'
