export const classes = {
  body_content: 'p-6 mt-14 flex justify-center items-center flex-col',
  center: 'text-center',
  company_content: 'flex justify-center items-center flex-col',
  content: 'w-full md:w-1/2 lg:w-1/3 px-4 mb-4',
  dates_content: 'flex justify-center flex-col',
  description_mobile: 'pl-2 pr-2 opacity-70 first-letter:ml-3 lg:hidden',
  description: 'mt-5 pl-2 pr-2 hidden lg:flex opacity-70',
  header_content: 'h-36 rounded-tr-lg rounded-tl-lg shadow-xl',
  logo_content: 'shadow-xl rounded-full',
  logo: 'mask mask-circle',
  name: 'text-2xl mb-2 font-bold text-white mt-12 custom-link no-decoration',
  rol_text: 'text-3xl opacity-70 mb-2 text-center',
  location_text: 'mb-2 opacity-100',
  rounded_card: 'rounded-lg shadow-lg',
  small_text: 'opacity-50 text-center',
}
